export const COMMANDS = {
  CREATE_CATALOG: "nr1.createCatalog",
  CATALOG_INFO: "nr1.catalogInfo",
  CATALOG_SUBMIT: "nr1.catalogSubmit",
  RUN_NERDPACK: "nr1.runNerdpack",
  CREATE_NERDPACK: "nr1.createNerdpack",
  CREATE_NERDLET: "nr1.createNerdlet",
  CREATE_LAUNCHER: "nr1.createLauncher",
  PUBLISH_NERDPACK: "nr1.publishNerdpack",
  DEPLOY_NERDPACK: "nr1.deployNerdpack",
  SUBSCRIBE_NERDPACK: "nr1.subscribeNerdpack",
  UNSUBSCRIBE_NERDPACK: "nr1.unsubscribeNerdpack",
  SELECT_PROFILE: "nr1.selectProfile",
  GENERATE_UUID: "nr1.generateUuid",
  OPEN_DEVELOPER_DOCS: "nr1.openDeveloperDocs",
};
